CREATE TYPE [api].[ParkingTicket] as TABLE
(
	[ParkingTicketId]				BIGINT		    NULL,
	[ATMId]                         BIGINT          NULL,
	[ParkingTicketCode]				Varchar(Max)    NULL,
	[ParkingTicketRefrence]			Varchar(Max)    NULL,
	[ParkedOn]						DATETIMEOFFSET  NULL,
	[ParkingDurationFrom]			DATETIMEOFFSET  NULL,
	[ParkingDurationTo]				DATETIMEOFFSET  NULL,
	[TotalDuration]					AS DATEDIFF(MINUTE, ParkingDurationFrom, ParkingDurationTo),
	[ParkingPriceId]                BIGINT          NULL,
	[VehicleNumber]					VARCHAR(MAX)    NULL,
	[PhoneNumber]					VARCHAR(MAX)    NULL,
	[IsExtended]                    BIT             NULL,
	[ExtendedOn]                    DATETIMEOFFSET  NULL,
	[ExtendedDurationForm]          DATETIMEOFFSET  NULL,
	[ExtendedDurationTo]            DATETIMEOFFSET  NULL,
	[ActualAmount]                  Decimal         NULL,
	[ExtendedAmount]                Decimal         NULL,
	[TotalAmount]                   DECIMAL         NULL,
	[Status]                        VARCHAR(MAX)    NULL,
	[CreatedBy]						BIGINT          NULL,
	[CreatedOn]						DATETIMEOFFSET  NULL,
	[ModifiedBy]					BIGINT          NULL,
	[ModifiedOn]					DATETIMEOFFSET  NULL,
	[IsActive]						BIT             NULL
)